### ISSUE TITLE
YouTube access token update failed

### ISSUE THREAD

**Issue by thaddeuskkr** [Walkyst/lavaplayer-fork#116]
Here's the error, and I've attached my Lavalink logs. Can't get `spring.log` as I'm running in a Docker container with no volume attached for logging.

```
2023-07-09T10:41:08.581Z ERROR 1 --- [back-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : YouTube access token update failed.

java.lang.RuntimeException: no identity in base-js found EID: d6169d89-9db6-4307-8b2b-e27f65798e83, js<redacted>
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:135) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.extractIdentity(YoutubeAccessTokenTracker.java:410) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.fetchTVScript(YoutubeAccessTokenTracker.java:398) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.requestAccessToken(YoutubeAccessTokenTracker.java:293) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.fetchAccessToken(YoutubeAccessTokenTracker.java:236) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.updateAccessToken(YoutubeAccessTokenTracker.java:151) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.getAccessToken(YoutubeAccessTokenTracker.java:203) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeHttpContextFilter.onRequest(YoutubeHttpContextFilter.java:75) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.http.SettableHttpRequestFilter.onRequest(SettableHttpRequestFilter.java:41) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:69) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.fetchScript(DefaultYoutubeTrackDetailsLoader.java:282) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:202) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:48) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:82) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:43) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-17c75f5.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:364) ~[lavaplayer-17c75f5.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

[lavalink.log](https://github.com/Walkyst/lavaplayer-fork/files/11994958/lavalink.log)

**Comment by zoli456** [comment]
I have the same problem.
```
2023-07-10 01:52:21.654 ERROR 12 --- [back-1-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : YouTube access token update failed.

java.lang.RuntimeException: no identity in base-js found EID: 0b22b6bd-965b-4cec-97a7-0f9256de3b5c, js <redacted>
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.throwWithDebugInfo(ExceptionTools.java:134) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.extractIdentity(YoutubeAccessTokenTracker.java:410) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.fetchTVScript(YoutubeAccessTokenTracker.java:398) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.requestAccessToken(YoutubeAccessTokenTracker.java:293) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.fetchAccessToken(YoutubeAccessTokenTracker.java:236) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.updateAccessToken(YoutubeAccessTokenTracker.java:151) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.getAccessToken(YoutubeAccessTokenTracker.java:203) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeHttpContextFilter.onRequest(YoutubeHttpContextFilter.java:71) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.http.SettableHttpRequestFilter.onRequest(SettableHttpRequestFilter.java:41) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:69) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.fetchScript(DefaultYoutubeTrackDetailsLoader.java:282) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:202) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:48) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:77) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:43) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.4.2.jar!/:na]
        at com.github.topisenpai.lavasrc.mirror.MirroringAudioTrack.process(MirroringAudioTrack.java:50) ~[lavasrc-plugin-3.2.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.4.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:361) ~[lavaplayer-1.4.2.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
```

**Comment by legouju** [comment]
Found a temp fix for the Youtube token failed thing

make a new Gmail account that's older than 18 and use that
do not add a phone number

**Comment by zoli456** [comment]
New accounts in the EU need ID or creditcard verfication to play age restricted content.

**Comment by topi314** [comment]
this has been fixed in
<https://github.com/lavalink-devs/lavaplayer/releases/tag/1.5.0>
<https://github.com/lavalink-devs/lavaplayer/releases/tag/2.0.0>

**Comment by zoli456** [comment]
Now show different error:
``` 
2023-08-03 09:23:19.529 ERROR 12 --- [ader-2-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : YouTube access token update failed.
java.io.IOException: Invalid status code for access token tv response: 400
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:157) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.requestAccessToken(YoutubeAccessTokenTracker.java:303) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.fetchAccessToken(YoutubeAccessTokenTracker.java:236) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.updateAccessToken(YoutubeAccessTokenTracker.java:151) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker.getAccessToken(YoutubeAccessTokenTracker.java:203) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeHttpContextFilter.onRequest(YoutubeHttpContextFilter.java:71) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.http.SettableHttpRequestFilter.onRequest(SettableHttpRequestFilter.java:41) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:69) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.fetchScript(DefaultYoutubeTrackDetailsLoader.java:282) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:202) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:48) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:228) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:252) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:248) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:101) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:66) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:44) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:216) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:147) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:428) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:410) ~[lavaplayer-1.5.0.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:208) ~[lavaplayer-1.5.0.jar!/:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
```

**Comment by topi314** [comment]
can you open a new issue on the new repo?

**Comment by zoli456** [comment]
I changed the password in the Google account and reauthorized the Lavalink server. Now works.
