### ISSUE TITLE
Decoding issue 

### ISSUE THREAD

**Issue by DolbyDev** [Walkyst/lavaplayer-fork#27]
This decoding error I get on videos (360D Audio) only. 
`e.g.` `https://www.youtube.com/watch?v=vG9EV6b5TJ0`
Is there a solution to this error?

```
[lava-daemon-pool-playback-1-thread-74908] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 6CeSz4vU1VA

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:294) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:250) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:39) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:57) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:49) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: java.lang.IllegalStateException: Failed to create a decoder instance with sample rate 48000 and channel count 4
	at com.sedmelluq.discord.lavaplayer.natives.opus.OpusDecoder.<init>(OpusDecoder.java:25) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.initialiseDecoder(OpusPacketRouter.java:194) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.checkDecoderNecessity(OpusPacketRouter.java:178) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.common.OpusPacketRouter.process(OpusPacketRouter.java:94) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaOpusTrackConsumer.consume(MatroskaOpusTrackConsumer.java:47) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:372) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:336) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:321) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:297) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:40) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:276) ~[lavaplayer-6ab48ea334f43e9acbfc35029ffd82be4906d0f2.jar!/:na]
	... 10 common frames omitted
```

**Comment by Walkyst** [comment]
This is because opus decoder with 4 channels can't be created, so this error is thrown, most likely will be fixed in 1.3.98
