### ISSUE TITLE
Cookie rejected

### ISSUE THREAD

**Issue by itsmishra19** [Walkyst/lavaplayer-fork#36]
Message:
```java
Cookie rejected [rj-listener-cookie="mfpxgbna4p00", version:0, domain:zeno.fm, path:/, expiry:null] Illegal 'domain' attribute "zeno.fm". Domain of origin: "stream.zenolive.com"
```

Stack Trace:
```java
  at org.apache.http.client.protocol.ResponseProcessCookies.processCookies(ResponseProcessCookies.java:123)
    at org.apache.http.client.protocol.ResponseProcessCookies.process(ResponseProcessCookies.java:93)
    at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:142)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:191)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
````

**Comment by Walkyst** [comment]
Link to sound source where i can reproduce this error?

**Comment by itsmishra19** [comment]
> Link to sound source where i can reproduce this error?

Sadly I don't

**Comment by Walkyst** [comment]
Then i can't todo something about this, maybe this source is restricted and requried some special headers to supplied
