### ISSUE TITLE
Invalid Status code from...

### ISSUE THREAD

**Issue by itsmishra19** [Walkyst/lavaplayer-fork#41]
Exception:
```java
Invalid status code from https://cf-hls-opus-media.sndcdn.com/media/325931/413077/LpmPTZmwPDqf.64.opus?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1vcHVzLW1lZGlhLnNuZGNkbi5jb20vbWVkaWEvKi8qL0xwbVBUWm13UERxZi42NC5vcHVzIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjQ5ODg3Nzg4fX19XX0_&Signature=Hzy7XVtSCVPZ85aG8fmlI86is3gGWxsWTiP6ZTgp2G6Pgz1XdwFM-JD0njJip1FBC8VsrN7GpY8j3M8iC9tFnm6-KrwT63oM31eGnaxldoMSp4fmJBWIkxBvGZtTwtNkzzRda2JXPeDvrqBzL6542c5CAyx49Hq4a9~NyA9C2Xj-db3jw38Hmoax4OUzGwinNNZ1xHJUuVGoaVu5kRMmYCT70IiQfaH-SYMjwQp4TQuDVqiLWrhXv9XAE~pwzuUgbLBBE8wUace6JDnjn64yiBwpczBwNddi-tx-W816hcdkYWZdVQz2IAkLJqOwYHTVDZCS~H3lbayMVPBDbsdS-Q__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ URL: 403
```

Stack:
```java
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
    at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:293)
    at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudM3uAudioTrack.process(SoundCloudM3uAudioTrack.java:41)
    at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
    at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.playFromIdentifier(SoundCloudAudioTrack.java:51)
    at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.process(SoundCloudAudioTrack.java:38)
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:830)
java.lang.RuntimeException: java.io.IOException: Invalid status code from https://cf-hls-opus-media.sndcdn.com/media/325931/413077/LpmPTZmwPDqf.64.opus?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1vcHVzLW1lZGlhLnNuZGNkbi5jb20vbWVkaWEvKi8qL0xwbVBUWm13UERxZi42NC5vcHVzIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjQ5ODg3Nzg4fX19XX0_&Signature=Hzy7XVtSCVPZ85aG8fmlI86is3gGWxsWTiP6ZTgp2G6Pgz1XdwFM-JD0njJip1FBC8VsrN7GpY8j3M8iC9tFnm6-KrwT63oM31eGnaxldoMSp4fmJBWIkxBvGZtTwtNkzzRda2JXPeDvrqBzL6542c5CAyx49Hq4a9~NyA9C2Xj-db3jw38Hmoax4OUzGwinNNZ1xHJUuVGoaVu5kRMmYCT70IiQfaH-SYMjwQp4TQuDVqiLWrhXv9XAE~pwzuUgbLBBE8wUace6JDnjn64yiBwpczBwNddi-tx-W816hcdkYWZdVQz2IAkLJqOwYHTVDZCS~H3lbayMVPBDbsdS-Q__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ URL: 403
    at com.sedmelluq.discord.lavaplayer.tools.http.HttpStreamTools.streamContent(HttpStreamTools.java:27)
    at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudM3uAudioTrack$SegmentTracker.getNextStream(SoundCloudM3uAudioTrack.java:128)
    at com.sedmelluq.discord.lavaplayer.tools.io.ChainedInputStream.loadNextStream(ChainedInputStream.java:25)
    at com.sedmelluq.discord.lavaplayer.tools.io.ChainedInputStream.read(ChainedInputStream.java:45)
    at org.apache.commons.io.input.ProxyInputStream.read(ProxyInputStream.java:59)
    at com.sedmelluq.discord.lavaplayer.tools.io.NonSeekableInputStream.read(NonSeekableInputStream.java:41)
    at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.checkNextBytes(MediaContainerDetection.java:126)
    at com.sedmelluq.discord.lavaplayer.container.ogg.OggPacketInputStream.readPageHeader(OggPacketInputStream.java:92)
    at com.sedmelluq.discord.lavaplayer.container.ogg.OggPacketInputStream.loadNextPage(OggPacketInputStream.java:158)
    at com.sedmelluq.discord.lavaplayer.container.ogg.OggPacketInputStream.loadNextNonEmptyPage(OggPacketInputStream.java:131)
    at com.sedmelluq.discord.lavaplayer.container.ogg.OggPacketInputStream.startNewPacket(OggPacketInputStream.java:76)
    at com.sedmelluq.discord.lavaplayer.container.ogg.opus.OggOpusTrackHandler.provideFrames(OggOpusTrackHandler.java:45)
    at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudOpusSegmentDecoder.playStream(SoundCloudOpusSegmentDecoder.java:61)
    at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudM3uAudioTrack.lambda$process$0(SoundCloudM3uAudioTrack.java:41)
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275)
    at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudM3uAudioTrack.process(SoundCloudM3uAudioTrack.java:41)
    at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
    at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.playFromIdentifier(SoundCloudAudioTrack.java:51)
    at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.process(SoundCloudAudioTrack.java:38)
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:830)
java.io.IOException: Invalid status code from https://cf-hls-opus-media.sndcdn.com/media/325931/413077/LpmPTZmwPDqf.64.opus?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1vcHVzLW1lZGlhLnNuZGNkbi5jb20vbWVkaWEvKi8qL0xwbVBUWm13UERxZi42NC5vcHVzIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjQ5ODg3Nzg4fX19XX0_&Signature=Hzy7XVtSCVPZ85aG8fmlI86is3gGWxsWTiP6ZTgp2G6Pgz1XdwFM-JD0njJip1FBC8VsrN7GpY8j3M8iC9tFnm6-KrwT63oM31eGnaxldoMSp4fmJBWIkxBvGZtTwtNkzzRda2JXPeDvrqBzL6542c5CAyx49Hq4a9~NyA9C2Xj-db3jw38Hmoax4OUzGwinNNZ1xHJUuVGoaVu5kRMmYCT70IiQfaH-SYMjwQp4TQuDVqiLWrhXv9XAE~pwzuUgbLBBE8wUace6JDnjn64yiBwpczBwNddi-tx-W816hcdkYWZdVQz2IAkLJqOwYHTVDZCS~H3lbayMVPBDbsdS-Q__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ URL: 403
    at com.sedmelluq.discord.lavaplayer.tools.http.HttpStreamTools.streamContent(HttpStreamTools.java:21)
    at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudM3uAudioTrack$SegmentTracker.getNextStream(SoundCloudM3uAudioTrack.java:128)
    at com.sedmelluq.discord.lavaplayer.tools.io.ChainedInputStream.loadNextStream(ChainedInputStream.java:25)
    at com.sedmelluq.discord.lavaplayer.tools.io.ChainedInputStream.read(ChainedInputStream.java:45)
    at org.apache.commons.io.input.ProxyInputStream.read(ProxyInputStream.java:59)
    at com.sedmelluq.discord.lavaplayer.tools.io.NonSeekableInputStream.read(NonSeekableInputStream.java:41)
    at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.checkNextBytes(MediaContainerDetection.java:126)
    at com.sedmelluq.discord.lavaplayer.container.ogg.OggPacketInputStream.readPageHeader(OggPacketInputStream.java:92)
    at com.sedmelluq.discord.lavaplayer.container.ogg.OggPacketInputStream.loadNextPage(OggPacketInputStream.java:158)
    at com.sedmelluq.discord.lavaplayer.container.ogg.OggPacketInputStream.loadNextNonEmptyPage(OggPacketInputStream.java:131)
    at com.sedmelluq.discord.lavaplayer.container.ogg.OggPacketInputStream.startNewPacket(OggPacketInputStream.java:76)
    at com.sedmelluq.discord.lavaplayer.container.ogg.opus.OggOpusTrackHandler.provideFrames(OggOpusTrackHandler.java:45)
    at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudOpusSegmentDecoder.playStream(SoundCloudOpusSegmentDecoder.java:61)
    at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudM3uAudioTrack.lambda$process$0(SoundCloudM3uAudioTrack.java:41)
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:275)
    at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudM3uAudioTrack.process(SoundCloudM3uAudioTrack.java:41)
    at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25)
    at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.playFromIdentifier(SoundCloudAudioTrack.java:51)
    at com.sedmelluq.discord.lavaplayer.source.soundcloud.SoundCloudAudioTrack.process(SoundCloudAudioTrack.java:38)
    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:830)
```
Message:
```java
Error in playback of O:https://api-v2.soundcloud.com/media/soundcloud:tracks:417229077/89f3d2b5-522c-4e6b-a9f1-a8446975d33c/stream/hls
```

**Comment by Walkyst** [comment]
Link to SoundCloud track?

**Comment by itsmishra19** [comment]
> Link to SoundCloud track?

I don't really have I got that error in prod it was caused by user.
