### ISSUE TITLE
Unexpected exception

### ISSUE THREAD

**Issue by DolbyDev** [Walkyst/lavaplayer-fork#43]
```
ERROR 20969 --- [lava-daemon-pool-playback-1-thread-2] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of 0itOCgJtNVU

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-d5535cf7fb7dc4e068dffda64097d6fc30767fdd.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-d5535cf7fb7dc4e068dffda64097d6fc30767fdd.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-d5535cf7fb7dc4e068dffda64097d6fc30767fdd.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: java.lang.RuntimeException: javax.script.ScriptException: ReferenceError: "g" is not defined. (eval#16) in eval at line number 16 at column number 0
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipher.transform(YoutubeSignatureCipher.java:59) ~[lavaplayer-d5535cf7fb7dc4e068dffda64097d6fc30767fdd.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:119) ~[lavaplayer-d5535cf7fb7dc4e068dffda64097d6fc30767fdd.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:89) ~[lavaplayer-d5535cf7fb7dc4e068dffda64097d6fc30767fdd.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:43) ~[lavaplayer-d5535cf7fb7dc4e068dffda64097d6fc30767fdd.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-d5535cf7fb7dc4e068dffda64097d6fc30767fdd.jar!/:na]
	... 4 common frames omitted
Caused by: javax.script.ScriptException: ReferenceError: "g" is not defined. (eval#16) in eval at line number 16 at column number 0
	at org.mozilla.javascript.engine.RhinoScriptEngine.eval(RhinoScriptEngine.java:122) ~[rhino-engine-1.7.14.jar!/:1.7.14]
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264) ~[java.scripting:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipher.transform(YoutubeSignatureCipher.java:56) ~[lavaplayer-d5535cf7fb7dc4e068dffda64097d6fc30767fdd.jar!/:na]
	... 8 common frames omitted
```

```
JVM: 11.0.14.1
Lavaplayer version: 84e5509765a5ee344b6db832505db48e7ed0dbd3 (custom)
```

**Comment by Walkyst** [comment]
Can you say date when this error happened?

UPD. Nvm, can reproduce this myself then will investigate what wrong

**Comment by DolbyDev** [comment]
> Can you say date when this error happened?

April 15. Have you tried and got the same exception?

**Comment by Walkyst** [comment]
Yes

**Comment by Walkyst** [comment]
Should be fixed in https://github.com/Walkyst/lavaplayer-fork/commit/8569cef30ad6f19498fa6c4c72821932fb2884eb
