### ISSUE TITLE
Throwing error when trying to play a specific video

### ISSUE THREAD

**Issue by Hydro001** [Walkyst/lavaplayer-fork#70]
I get this error when trying to play https://www.youtube.com/watch?v=I_6ZcOo6pnk :
```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:354) ~[lavaplayer-1.3.99.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.3.99-original
  os.arch: amd64
  os.name: Windows 10
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 17.0.4.1
  java.runtime.version: 17.0.4.1+1-LTS-2
  java.vm.version: 17.0.4.1+1-LTS-2
Caused by: java.lang.RuntimeException: java.io.EOFException
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:56) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:58) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:50) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.3.99.jar!/:na]
        ... 4 common frames omitted
Caused by: java.io.EOFException: null
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:273) ~[na:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readFixedSizeEbmlInteger(MatroskaEbmlReader.java:24) ~[lavaplayer-1.3.99.jar!/:na]     
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.asLong(MatroskaFileReader.java:109) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseCuePoint(MatroskaStreamingFile.java:191) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseCues(MatroskaStreamingFile.java:170) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseSegmentElement(MatroskaStreamingFile.java:130) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:92) ~[lavaplayer-1.3.99.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51) ~[lavaplayer-1.3.99.jar!/:na]
        ... 9 common frames omitted
```

I used Lavalink and i opened an error on their repo they then said me that it probably came from Lavaplayer (That's also what i see in the logs that i provided above).

Thank you and have a nice day.

**Comment by Walkyst** [comment]
Tested and it playing fine, although this videos doesn't have audio so what point of playing it

**Comment by Hydro001** [comment]
> Tested and it playing fine, although this videos doesn't have audio so what point of playing it

It doesn't play for me but as you said there's no point to play it anyway, it was just to let you know that it did that with this kind of videos.

Have a nice day.
