### ISSUE TITLE
Getting unsatisfied link error running on macos Ventura 13.2.1

### ISSUE THREAD

**Issue by kanishkdebnath-bst** [Walkyst/lavaplayer-fork#83]
java.lang.UnsatisfiedLinkError: 'void com.sedmelluq.discord.lavaplayer.natives.statistics.CpuStatisticsLibrary.getSystemTimes(long[])'
	at com.sedmelluq.discord.lavaplayer.natives.statistics.CpuStatisticsLibrary.getSystemTimes(Native Method) ~[main-1.3.99.2-original.jar:na]
	at com.sedmelluq.discord.lavaplayer.natives.statistics.CpuStatistics.getSystemTimes(CpuStatistics.java:22) ~[main-1.3.99.2-original.jar:na]
	at com.sedmelluq.discord.lavaplayer.node.StatisticsManager.pollCpuStatistics(StatisticsManager.java:51) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

**Comment by Walkyst** [comment]
Lavaplayer node not really maintained and shouldn't be used, maybe Lavalink is something you looking

**Comment by kanishkdebnath-bst** [comment]
I am trying to fix some issues for twitch streams and vimeo videos for which I need to use this within lavalink. But I am unable to build due to the above error.

**Comment by Walkyst** [comment]
You can just run lavaplayer itself for test purposes
