### ISSUE TITLE
Loading from youtube song error

### ISSUE THREAD

**Issue by Mrolcraft** [Walkyst/lavaplayer-fork#92]
Hi guys,

I have this error and i don't find how to solve it.

Thanks
```
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a YouTube track failed.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:240)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:252)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:248)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:101)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:66)
        at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:44)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:216)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:147)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:449)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:431)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98)
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.4.0-original
  os.arch: amd64
  os.name: Linux
  os.version: 4.9.0
  java.vendor: Oracle Corporation
  java.version: 1.8.0_332
  java.runtime.version: 1.8.0_332-8u332-ga-1~deb9u1-b09
  java.vm.version: 25.332-b09
Caused by: org.apache.commons.logging.LogConfigurationException: java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl (Caused by java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl)
        at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1276)
        at org.apache.commons.logging.LogFactory$2.run(LogFactory.java:1065)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.commons.logging.LogFactory.newFactory(LogFactory.java:1062)
        at org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:650)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:685)
        at org.apache.http.conn.ssl.DefaultHostnameVerifier.<init>(DefaultHostnameVerifier.java:82)
        at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedHttpClientBuilder.createConnectionSocketFactory(ExtendedHttpClientBuilder.java:100)
        at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedHttpClientBuilder.createConnectionManager(ExtendedHttpClientBuilder.java:94)
        at com.sedmelluq.discord.lavaplayer.tools.http.ExtendedHttpClientBuilder.build(ExtendedHttpClientBuilder.java:56)
        at com.sedmelluq.discord.lavaplayer.tools.io.AbstractHttpInterfaceManager.getSharedClient(AbstractHttpInterfaceManager.java:83)
        at com.sedmelluq.discord.lavaplayer.tools.io.ThreadLocalHttpInterfaceManager.getInterface(ThreadLocalHttpInterfaceManager.java:34)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.getHttpInterface(YoutubeAudioSourceManager.java:186)
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:227)
        ... 16 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.impl.LogFactoryImpl
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1131)
        ... 29 more

```

**Comment by jocull** [comment]
Only guessing, but...

- Are all of the dependencies loading properly?
- Have you tried JDK 11?
